[package]
name = "facetract"
version = "0.1.0"
authors = ["Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"

[dependencies]
tensorflow = "0.15"
image = { version = "0.23", default-features = false }
num-traits = "0.2"
thiserror = "1.0"

[dev-dependencies]
image = "0.23"
